In [1]:
import pandas as pd
d_train = pd.read_csv("titanic_data/train.csv")
d_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
d_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [3]:
def extract_title(x):
    x = x.split()
    for y in x:
        if y[-1]=='.':
            return y

In [4]:
d_train["Name"].map(lambda x: extract_title(x)).value_counts()

Name
Mr.          517
Miss.        182
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Mlle.          2
Major.         2
Col.           2
Countess.      1
Capt.          1
Ms.            1
Sir.           1
Lady.          1
Mme.           1
Don.           1
Jonkheer.      1
Name: count, dtype: int64

In [5]:
def feature_engineering(data):
    data = data.copy()
    data.loc[:, "Sex"] = data["Sex"].map({"male":1, "female":2}).astype(int)
    data.loc[data["Age"].isna(), "Age"] = data["Age"].mode()[0]
    data.loc[data["Embarked"].isna(), "Embarked"] = data["Embarked"].mode()[0]
    data.loc[:, "Embarked"] = data["Embarked"].map({"S":1, "C":2, "Q":3})
    data.loc[:, "Family_size"] = data["SibSp"]+data["Parch"]+1
    data.loc[:, "IsAlone"] = (data["Family_size"]==1).astype(int)
    data.loc[:, "HasDeck"] = data["Cabin"].notna().astype(int)
    data.loc[:, "Title"] = data["Name"].map(lambda x: extract_title(x)).map({"Mr.": 1, "Miss.": 2, "Mrs.": 3, "Master.":4, "Dr.":5, "Rev.":6, "Mlle.":7, "Major.":7, "Col.":7, "Countess.":7, "Capt.":7, "Ms.":7, "Sir.":7, "Lady.":7, "Mme.":7, "Don.":7, "Jonkheer":7})
    data.loc[data["Title"].isna(), "Title"] = data["Title"].mode()[0].astype(int)
    data.loc[:, "Title"] = data["Title"].astype(int)
    return data

In [6]:
d_train = feature_engineering(d_train)
d_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_size,IsAlone,HasDeck,Title
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,1,2,0,0,1.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,38.0,1,0,PC 17599,71.2833,C85,2,2,0,1,3.0
2,3,1,3,"Heikkinen, Miss. Laina",2,26.0,0,0,STON/O2. 3101282,7.9250,NaN,1,1,1,0,2.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",2,35.0,1,0,113803,53.1000,C123,1,2,0,1,3.0
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,1,1,1,0,1.0

In [7]:
d_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
 12  Family_size  891 non-null    int64
 13  IsAlone      891 non-null    int64
 14  HasDeck      891 non-null    int64
 15  Title        891 non-null    float64
dtypes: float64(3), int64(8), object(5)
memory usage: 111.5+ KB

In [8]:
for col in ["Sex", "Embarked"]:
    d_train[col] = pd.to_numeric(d_train[col]).astype(int)

In [9]:
d_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    int64
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    int64
 12  Family_size  891 non-null    int64
 13  IsAlone      891 non-null    int64
 14  HasDeck      891 non-null    int64
 15  Title        891 non-null    float64
dtypes: float64(3), int64(10), object(3)
memory usage: 111.5+ KB

In [10]:
X = d_train.iloc[:, [2,4,5,6,7,9,11,12,13,14,15]]
Y = d_train.iloc[:, [1]]
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [11]:
x_train,x_test, y_train, y_test = train_test_split(X,Y, train_size=0.8)

In [12]:
from sklearn.metrics import accuracy_score
models = [LogisticRegression, RandomForestClassifier, GradientBoostingClassifier, XGBClassifier]
accuracy_scores = []
for model in models:
    model1 = model()
    model1.fit(x_train, y_train)
    predicts = model1.predict(x_test)
    accuracy_scores.append(accuracy_score(y_test, predicts))
print(accuracy_scores)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[0.8156424581005587, 0.7877094972067039, 0.7932960893854749, 0.7988826815642458]

In [13]:
comp_data = pd.read_csv("titanic_data/test.csv")
comp_data = feature_engineering(comp_data)
x_comp = comp_data.iloc[:, [1,3,4,5,6,8,10,11,12,13,14]]
x_comp.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Family_size,IsAlone,HasDeck,Title
0,3,1,34.5,0,0,7.8292,3,1,1,0,1.0
1,3,2,47.0,1,0,7.0000,1,2,0,0,3.0
2,2,1,62.0,0,0,9.6875,3,1,1,0,1.0
3,3,1,27.0,0,0,8.6625,1,1,1,0,1.0
4,3,2,22.0,1,1,12.2875,1,3,0,0,3.0

In [14]:
X.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Family_size,IsAlone,HasDeck,Title
0,3,1,22.0,1,0,7.2500,1,2,0,0,1.0
1,1,2,38.0,1,0,71.2833,2,2,0,1,3.0
2,3,2,26.0,0,0,7.9250,1,1,1,0,2.0
3,1,2,35.0,1,0,53.1000,1,2,0,1,3.0
4,3,1,35.0,0,0,8.0500,1,1,1,0,1.0

In [15]:
x_comp.loc[x_comp["Fare"].isna(), "Fare"] = x_comp["Fare"].mean()
x_comp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Pclass       418 non-null    int64
 1   Sex          418 non-null    object
 2   Age          418 non-null    float64
 3   SibSp        418 non-null    int64
 4   Parch        418 non-null    int64
 5   Fare         418 non-null    float64
 6   Embarked     418 non-null    object
 7   Family_size  418 non-null    int64
 8   IsAlone      418 non-null    int64
 9   HasDeck      418 non-null    int64
 10  Title        418 non-null    float64
dtypes: float64(3), int64(6), object(2)
memory usage: 36.1+ KB

In [16]:
model = models[accuracy_scores.index(max(accuracy_scores))]()
model.fit(X,Y)
predictions = model.predict(x_comp)
predictions = pd.Series(predictions, name = "Survived", index=comp_data["PassengerId"])
predictions

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

PassengerId
892     0
893     0
894     0
895     0
896     1
       ..
1305    0
1306    1
1307    0
1308    0
1309    0
Name: Survived, Length: 418, dtype: int64

In [17]:
predictions.to_csv("titanic_data/output.csv")